steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Backend Image"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cmo-backend-api:$COMMIT_SHA", "."]

  # Step 2: Push the Docker image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Backend Image"
    args: ["push", "gcr.io/$PROJECT_ID/cmo-backend-api:$COMMIT_SHA"]

  # Step 3: Deploy Cloud Run Job for DB migration and seeding
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Migration Job"
    entrypoint: "bash"
    secretEnv:
      - DB_INSTANCE_NAME
      - DATABASE_URL_SECRET
      - PAGESPEED_API_KEY_SECRET
      - GOOGLE_CLIENT_ID_SECRET
      - GOOGLE_CLIENT_SECRET_SECRET
      - GOOGLE_CALLBACK_URL_SECRET
      - SESSION_SECRET_SECRET
      - YOUTUBE_API_KEY_SECRET
      - OPENAI_API_KEY_SECRET
      - NEXT_PUBLIC_BASE_URL_SECRET
      - JWT_SECRET_SECRET
      - CHECKOUT_SECRET_KEY_SECRET
      - CHECKOUT_WEBHOOK_SECRET_SECRET
      - CHECKOUT_WEBHOOK_AUTH_KEY_SECRET
      - CKO_PROCESSING_CHANNEL_ID_SECRET
      - NODE_SECRET
      - SCRAPPER_CREATOR_APIKEY_SECRET
      - MODE
    args:
      - "-c"
      - |
        gcloud run jobs deploy cmo-db-migration-job \
          --image=gcr.io/$PROJECT_ID/cmo-backend-api:$COMMIT_SHA \
          --region=us-central1 \
          --set-cloudsql-instances=$$DB_INSTANCE_NAME \
          --set-env-vars=TASK=migrate \
          --set-secrets=DATABASE_URL=DATABASE_URL_SECRET:latest \
          --set-secrets=PAGESPEED_API_KEY=pagespeed-api-key:latest \
          --set-secrets=GOOGLE_CLIENT_ID=backend-google-client-id:latest \
          --set-secrets=GOOGLE_CLIENT_SECRET=backend-google-client-secret:latest \
          --set-secrets=GOOGLE_CALLBACK_URL=google-callback-url:latest \
          --set-secrets=SESSION_SECRET=session-secret:latest \
          --set-secrets=YOUTUBE_API_KEY=youtube-api-key:latest \
          --set-secrets=OPENAI_API_KEY=openai-api-key:latest \
          --set-secrets=NEXT_PUBLIC_BASE_URL=next-public-base-url:latest \
          --set-secrets=JWT_SECRET=jwt-secret:latest \
          --set-secrets=CHECKOUT_SECRET_KEY=checkout-secret-key:latest \
          --set-secrets=CHECKOUT_WEBHOOK_SECRET=checkout-webhook-secret:latest \
          --set-secrets=CHECKOUT_WEBHOOK_AUTH_KEY=checkout-webhook-auth-key:latest \
          --set-secrets=CKO_PROCESSING_CHANNEL_ID=cko-processing-channel-id:latest \
          --set-secrets=NODE=node-secret:latest \
          --set-secrets=SCRAPPER_CREATOR_APIKEY=SCRAPPER_CREATOR_APIKEY:latest \
          --set-secrets=MODE=MODE:latest \
          --max-retries=3 \
          --task-timeout=10m

  # Step 4: Execute the migration job
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Execute Migration Job"
    entrypoint: "gcloud"
    args:
      - "run"
      - "jobs"
      - "execute"
      - "cmo-db-migration-job"
      - "--region=us-central1"
      - "--wait"

  # Step 5: Deploy the backend Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Backend Service"
    entrypoint: "bash"
    secretEnv:
      - DB_INSTANCE_NAME
      - DATABASE_URL_SECRET
      - PAGESPEED_API_KEY_SECRET
      - GOOGLE_CLIENT_ID_SECRET
      - GOOGLE_CLIENT_SECRET_SECRET
      - GOOGLE_CALLBACK_URL_SECRET
      - SESSION_SECRET_SECRET
      - YOUTUBE_API_KEY_SECRET
      - OPENAI_API_KEY_SECRET
      - NEXT_PUBLIC_BASE_URL_SECRET
      - JWT_SECRET_SECRET
      - CHECKOUT_SECRET_KEY_SECRET
      - CHECKOUT_WEBHOOK_SECRET_SECRET
      - CHECKOUT_WEBHOOK_AUTH_KEY_SECRET
      - CKO_PROCESSING_CHANNEL_ID_SECRET
      - NODE_SECRET
      - SCRAPPER_CREATOR_APIKEY_SECRET
      - MODE
    args:
      - "-c"
      - |
        gcloud run deploy cmo-backend-api \
          --image=gcr.io/$PROJECT_ID/cmo-backend-api:$COMMIT_SHA \
          --region=us-central1 \
          --platform=managed \
          --add-cloudsql-instances=$$DB_INSTANCE_NAME \
          --set-env-vars=TASK=start \
          --set-secrets=DATABASE_URL=DATABASE_URL_SECRET:latest \
          --set-secrets=PAGESPEED_API_KEY=pagespeed-api-key:latest \
          --set-secrets=GOOGLE_CLIENT_ID=backend-google-client-id:latest \
          --set-secrets=GOOGLE_CLIENT_SECRET=backend-google-client-secret:latest \
          --set-secrets=GOOGLE_CALLBACK_URL=google-callback-url:latest \
          --set-secrets=SESSION_SECRET=session-secret:latest \
          --set-secrets=YOUTUBE_API_KEY=youtube-api-key:latest \
          --set-secrets=OPENAI_API_KEY=openai-api-key:latest \
          --set-secrets=NEXT_PUBLIC_BASE_URL=next-public-base-url:latest \
          --set-secrets=JWT_SECRET=jwt-secret:latest \
          --set-secrets=CHECKOUT_SECRET_KEY=checkout-secret-key:latest \
          --set-secrets=CHECKOUT_WEBHOOK_SECRET=checkout-webhook-secret:latest \
          --set-secrets=CHECKOUT_WEBHOOK_AUTH_KEY=checkout-webhook-auth-key:latest \
          --set-secrets=CKO_PROCESSING_CHANNEL_ID=cko-processing-channel-id:latest \
          --set-secrets=NODE=node-secret:latest \
          --set-secrets=SCRAPPER_CREATOR_APIKEY=SCRAPPER_CREATOR_APIKEY:latest \
          --set-secrets=MODE=MODE:latest \
          --no-allow-unauthenticated \
          --port=3001

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db-instance-name/versions/latest
      env: "DB_INSTANCE_NAME"
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL_SECRET/versions/latest
      env: "DATABASE_URL_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/pagespeed-api-key/versions/latest
      env: "PAGESPEED_API_KEY_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/backend-google-client-id/versions/latest
      env: "GOOGLE_CLIENT_ID_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/backend-google-client-secret/versions/latest
      env: "GOOGLE_CLIENT_SECRET_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/google-callback-url/versions/latest
      env: "GOOGLE_CALLBACK_URL_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/session-secret/versions/latest
      env: "SESSION_SECRET_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/youtube-api-key/versions/latest
      env: "YOUTUBE_API_KEY_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/openai-api-key/versions/latest
      env: "OPENAI_API_KEY_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/next-public-base-url/versions/latest
      env: "NEXT_PUBLIC_BASE_URL_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/jwt-secret/versions/latest
      env: "JWT_SECRET_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/checkout-secret-key/versions/latest
      env: "CHECKOUT_SECRET_KEY_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/checkout-webhook-secret/versions/latest
      env: "CHECKOUT_WEBHOOK_SECRET_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/checkout-webhook-auth-key/versions/latest
      env: "CHECKOUT_WEBHOOK_AUTH_KEY_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/cko-processing-channel-id/versions/latest
      env: "CKO_PROCESSING_CHANNEL_ID_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/node-secret/versions/latest
      env: "NODE_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/SCRAPPER_CREATOR_APIKEY/versions/latest
      env: "SCRAPPER_CREATOR_APIKEY_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/MODE/versions/latest
      env: "MODE"

options:
  logging: CLOUD_LOGGING_ONLY
